# Generated by Django 3.0.5 on 2020-05-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0003_auto_20200527_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='flowershop.Category'),
        ),
    ]
