# Generated by Django 3.0.5 on 2020-05-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0004_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
