# Generated by Django 3.0.5 on 2020-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0007_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
