# Generated by Django 3.0.5 on 2020-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0008_auto_20200601_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='topics',
            field=models.ManyToManyField(to='flowershop.Topic'),
        ),
    ]
