# Generated by Django 3.0.5 on 2020-06-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0012_auto_20200608_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Wait for confirmation'), (1, 'Confirmed - processing'), (2, 'Delivering')], default=0),
        ),
    ]
