# Generated by Django 3.0.5 on 2020-06-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0013_auto_20200609_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Percent'), (1, 'Amount')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting for confirmation'), (1, 'Confirmed - processing'), (2, 'Delivering')], default=0),
        ),
    ]
