# Generated by Django 3.0.5 on 2020-06-09 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0014_auto_20200609_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='type',
            new_name='discount_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_max_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
