# Generated by Django 3.0.5 on 2020-06-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0017_auto_20200609_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background',
            field=models.ImageField(default='utl', upload_to='blog_background'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting for confirmation'), (1, 'Confirmed - processing'), (2, 'Delivering'), (3, 'Delivered')], default=0),
        ),
    ]
