# Generated by Django 3.0.5 on 2020-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0019_auto_20200617_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='a', upload_to='topic_image'),
            preserve_default=False,
        ),
    ]
