# Generated by Django 3.0.5 on 2020-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0022_auto_20200619_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='flowershop.Tag'),
        ),
    ]
