# Generated by Django 3.0.5 on 2020-06-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0023_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
