# Generated by Django 3.0.5 on 2020-07-06 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0025_auto_20200706_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
